version: '3'
services:
  algalog:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: algalog
    container_name: algalog
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/algalog
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - db
      - flyway
    links:
      - db
  db:
    image: mysql:8
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=algalog
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123
      - MYSQL_ROOT_PASSWORD=dev123
    volumes:
      - ./db:/var/lib/mysql
  flyway:
    image: boxfuse/flyway:latest
    container_name: flyway
    command: -url=jdbc:mysql://db:3306/algalog -user=root -password=dev123 migrate
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db
    links:
      - db
volumes:
  db:
  migration: